version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=django36.settings
    depends_on:
      - postgres
      - redis
      - celery-worker
      - celery-beat

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  redis:
    image: redis:6

  celery-worker:
    build: .
    command: celery --app django36 worker -l info
    depends_on:
      - web
      - redis
      - postgres

  celery-beat:
    build: .
    command: celery --app django36 beat -l info
    depends_on:
      - web
      - redis
      - postgres


  nginx:
    image: nginx:1.19.0
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

networks:
  default:
    driver: bridge